# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/healthcheck.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_file("protos/healthcheck.proto", :syntax => :proto3) do
    add_message "deployer.Input" do
    end
    add_message "deployer.Output" do
      optional :message, :string, 1
    end
  end
end

module Deployer
  Input = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("deployer.Input").msgclass
  Output = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("deployer.Output").msgclass
end
