# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: protos/healthcheck.proto for package 'deployer'

require 'grpc'
require 'healthcheck_pb'

module Deployer
  module Healthcheck
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'deployer.Healthcheck'

      rpc :SayHello, ::Deployer::Input, ::Deployer::Output
    end

    Stub = Service.rpc_stub_class
  end
end
